apiVersion: skaffold/v3
kind: Config
metadata:
  name: app
build:
  platforms: ["linux/amd64"]
  artifacts:
  - image: productcatalogservice # Kustomize（通过 Skaffold）通过 image 字段的值 来匹配配置文件和微服务。
    context: src/productcatalogservice
  - image: frontend
    context: src/frontend
  - image: currencyservice
    context: src/currencyservice
  - image: shippingservice
    context: src/shippingservice
  - image: paymentservice
    context: src/paymentservice
  - image: adservice
    context: src/adservice
  - image: recommendationservice
    context: src/recommendationservice
  - image: emailservice
    context: src/emailservice
  - image: cartservice
    context: src/cartservice
  - image: checkoutservice
    context: src/checkoutservice
  tagPolicy:
    gitCommit: {}
  local:
    useDockerCLI: true     # 必须启用才能使用 BuildKit
    useBuildkit: true      # 启用 BuildKit
manifests:
  kustomize:
    paths:
    - kubernetes-manifests
---
apiVersion: skaffold/v3
kind: Config
metadata:
  name: loadgenerator
requires:
- configs:
  - app
build:
  artifacts:
  - image: loadgenerator
    context: src/loadgenerator
  tagPolicy:
    gitCommit: {}
  local:
    useDockerCLI: true     # 必须启用才能使用 BuildKit
    useBuildkit: true      # 启用 BuildKit
manifests:
  rawYaml:
  - ./kubernetes-manifests/loadgenerator.yaml
deploy:
  kubectl: {}
profiles: # 该预设用于谷歌平台
- name: gcb
  build:
    googleCloudBuild:
      diskSizeGb: 300
      machineType: N1_HIGHCPU_32
      timeout: 4000s
