apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - dex.

namesapce: dex

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: github-client
    behavior: replace
    envs:
      - .github-client.env

  - name: dex.example.com.tls
    type: kubernetes.io/tls
    behavior: replace
    files:
      - tls.crt=ssl/cert.pem
      - tls.key=ssl/key.pem