# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: "Continuous Integration - Main"

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

on:
  push:
    branches: [ "main", "cicd-pipeline" ]
    paths:
      - 'src/**'
      - '.github/workflows/ci-main-build.yaml'
      - '!**/README.md'

jobs:
  skaffold-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install skaffold
      run: |
        curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
        sudo install skaffold /usr/local/bin/
    - name: Skaffold Diagnose
      run: |
        skaffold diagnose --check
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build All Images
      run: |
        skaffold build --push=false --cache-artifacts=true
